"""Gangent 第一版 runtime 骨架。

这里统一导出核心数据结构，方便后续其他模块直接从 gangent 包引用。
"""

from .models import (
    ActionDecision,
    AgentPhase,
    AgentState,
    AuditEntry,
    DecisionType,
    Message,
    MessageRole,
    PlanStep,
    PlanStepStatus,
    PolicyDecision,
    PolicyMode,
    RuntimeStats,
    Task,
    TaskInput,
    TaskStatus,
    ToolCallRecord,
    ToolResult,
)
from .audit import append_audit_record, default_audit_path
from .budget_stats import (
    BudgetRecommendation,
    BudgetSample,
    PlannerQualityReport,
    evaluate_planner_quality,
    planner_feedback_for_task,
    recommend_budget,
)
from .context_manager import DynamicContextPack, build_dynamic_context_pack
from .planner_eval import (
    append_planner_evaluation,
    default_planner_eval_path,
    load_planner_evaluations,
    summarize_planner_evaluations,
)
from .embeddings import (
    EmbeddingBackendConfig,
    EmbeddingBackendKind,
    EmbeddingEnvironment,
    create_embedding_backend,
    detect_embedding_environment,
)
from .hooks import HookEvent, HookManager
from .events import EventRuntimeState, EventTransition, transition_from_interrupt
from .mcp_adapter import MCPToolSpec, adapt_mcp_tool, adapt_mcp_tools, mcp_tool_id
from .memory_graph import MemoryContextPack, MemoryLayer, build_memory_context_pack
from .metrics import classification_metrics, summarize_audit_jsonl
from .model_input import ModelInput, build_model_input, build_model_messages
from .output import print_result, result_to_dict
from .permissions import PermissionProfile, default_permission_profile
from .policy import check_policy
from .providers import create_llm_client
from .rag import (
    RetrievalConfig,
    RetrievalLogEntry,
    SearchResult,
    TextChunk,
    build_chunks,
    search_chunks,
    search_context,
)
from .runtime import RuntimeResult, RuntimeStepTrace, run_task
from .session import (
    SessionState,
    SessionTurn,
    build_task_input_from_session,
    create_session,
    reset_session,
    update_session_from_result,
)
from .session_store import (
    default_session_path,
    load_or_create_session,
    load_session,
    save_session,
)
from .secret_guard import (
    contains_secret,
    is_sensitive_path,
    redact_data,
    redact_secrets,
    scan_secrets,
)
from .tool_schema import available_tool_schemas, to_deepseek_tools
from .tool_runtime import (
    compile_python,
    edit_file,
    ensure_workspace,
    execute_tool_call,
    export_artifact,
    fetch_url,
    grep_files,
    git_diff,
    git_status,
    list_files,
    memory_add,
    read_file,
    read_many_files,
    run_tests,
    scratchpad_note,
    write_file,
)

__all__ = [
    "ActionDecision",
    "AgentPhase",
    "AgentState",
    "AuditEntry",
    "DecisionType",
    "Message",
    "MessageRole",
    "PlanStep",
    "PlanStepStatus",
    "PolicyDecision",
    "PolicyMode",
    "RuntimeStats",
    "Task",
    "TaskInput",
    "TaskStatus",
    "ToolCallRecord",
    "ToolResult",
    "ModelInput",
    "append_audit_record",
    "append_planner_evaluation",
    "available_tool_schemas",
    "BudgetRecommendation",
    "BudgetSample",
    "PlannerQualityReport",
    "build_model_input",
    "build_model_messages",
    "build_dynamic_context_pack",
    "build_memory_context_pack",
    "check_policy",
    "classification_metrics",
    "compile_python",
    "create_llm_client",
    "create_embedding_backend",
    "default_audit_path",
    "default_permission_profile",
    "default_planner_eval_path",
    "edit_file",
    "ensure_workspace",
    "execute_tool_call",
    "evaluate_planner_quality",
    "EventRuntimeState",
    "EventTransition",
    "export_artifact",
    "fetch_url",
    "grep_files",
    "git_diff",
    "git_status",
    "HookEvent",
    "HookManager",
    "EmbeddingBackendConfig",
    "EmbeddingBackendKind",
    "EmbeddingEnvironment",
    "list_files",
    "detect_embedding_environment",
    "MCPToolSpec",
    "MemoryContextPack",
    "MemoryLayer",
    "adapt_mcp_tool",
    "adapt_mcp_tools",
    "mcp_tool_id",
    "read_file",
    "read_many_files",
    "recommend_budget",
    "run_tests",
    "scratchpad_note",
    "search_context",
    "write_file",
    "RuntimeResult",
    "RuntimeStepTrace",
    "run_task",
    "SessionState",
    "SessionTurn",
    "build_task_input_from_session",
    "create_session",
    "reset_session",
    "update_session_from_result",
    "default_session_path",
    "load_or_create_session",
    "load_session",
    "load_planner_evaluations",
    "memory_add",
    "print_result",
    "PermissionProfile",
    "planner_feedback_for_task",
    "contains_secret",
    "is_sensitive_path",
    "redact_data",
    "redact_secrets",
    "scan_secrets",
    "RetrievalConfig",
    "RetrievalLogEntry",
    "SearchResult",
    "TextChunk",
    "build_chunks",
    "search_chunks",
    "save_session",
    "result_to_dict",
    "summarize_audit_jsonl",
    "summarize_planner_evaluations",
    "to_deepseek_tools",
    "transition_from_interrupt",
]
